### ISSUE TITLE
Error Code 403

### ISSUE THREAD

**Issue by SpatzlHD** [KTNG-3/val-api#2]
When i am trying to use the .Auth.Account.login() method to login i am getting a 1020 Error Code.

**Comment by SpatzlHD** [comment]
> When i am trying to use the .Auth.Account.login() method to login i am getting a 1020 Error Code.

Wrong Error Code... The Error Code is 403 not 1020

**Comment by KTNG-3** [comment]
sorry for not reading

Is there still a problem now?
